# Generated by Django 2.0.5 on 2018-06-01 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thread',
            old_name='thead_text',
            new_name='thread_text',
        ),
    ]
